const Info = [{
        "login": "AlexandraMGheorghe",
        "id": 77536806,
        "node_id": "MDQ6VXNlcjc3NTM2ODA2",
        "avatar_url": "https://avatars.githubusercontent.com/u/77536806?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AlexandraMGheorghe",
        "html_url": "https://github.com/AlexandraMGheorghe",
        "followers_url": "https://api.github.com/users/AlexandraMGheorghe/followers",
        "following_url": "https://api.github.com/users/AlexandraMGheorghe/following{/other_user}",
        "gists_url": "https://api.github.com/users/AlexandraMGheorghe/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AlexandraMGheorghe/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AlexandraMGheorghe/subscriptions",
        "organizations_url": "https://api.github.com/users/AlexandraMGheorghe/orgs",
        "repos_url": "https://api.github.com/users/AlexandraMGheorghe/repos",
        "events_url": "https://api.github.com/users/AlexandraMGheorghe/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AlexandraMGheorghe/received_events",
        "type": "User",
        "site_admin": false,
        "name": null,
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 3,
        "public_gists": 0,
        "followers": 2,
        "following": 1,
        "created_at": "2021-01-16T13:25:14Z",
        "updated_at": "2023-03-21T17:55:05Z"
    }
]
export default Info;